name: Build

on:
  push:
  workflow_dispatch:
  workflow_run:
    workflows: ["update"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.x
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm exec playwright install
        working-directory: ./packages/end-to-end
      - run: pnpm test:e2e
      - run: pnpm build
